@startuml
-> CellMouseBehavior:setOn\nMouse\nDragged()
CellMouseBehavior -> CellList: startDrag(thisID)
CellList -> CellList: get(thisId)
CellList -> CellList: setDraggedCell(thisID)
CellList -> CellList: insertPlaceholder()
CellList -> CellList: getIndex(thisID)
CellList -> CellList: add(placeholder, thisIndex)1
CellMouseBehavior -> CellPlacement: followDrag()
CellPlacement -> CellPlacement: setPosition()
CellPlacement -> CellPlacement: updateListIndex()
CellPlacement -> CellList: moveTo()
CellList -> CellList: onMoveTo()
CellList -> CellPlacement: (for each\nObserver)\nupdate()
CellPlacement -> CellPlacement: placeAtNewIndex()
CellList -> CellList: onFinished\nMoving()
CellList -> CellAnimationBehavior: (for each\nObserver)\nupdate()
CellAnimationBehavior -> CellAnimationBehavior: animateTo()
@enduml


