@startuml
!include ../Declarations.puml!History
!include ../Declarations.puml!DaysEditorState
!include ../Declarations.puml!PlaceholderCell
!include ../Declarations.puml!FullDaysEditor
!include ../Declarations.puml!DaysEditor
!include ../Declarations.puml!CellListFullFeatured
!include ../Declarations.puml!CellListNoPush
!include ../Declarations.puml!CellGridFullFeatured
!include ../Declarations.puml!CellGridNoPush
!include ../Declarations.puml!CellData
!include ../Declarations.puml!Cell
!include ../Declarations.puml!CellAnimationBehavior
!include ../Declarations.puml!CellMouseBehavior
!include ../Declarations.puml!CellPlacement
!include ../Declarations.puml!CellDesigner
!include ../Declarations.puml!DayCellDesigner
!include ../Declarations.puml!DayCellAnimationBehavior
!include ../Declarations.puml!FutureDayCellMouseBehavior
!include ../Declarations.puml!PastDayCellMouseBehavior
!include ../Declarations.puml!DayCellPlacement
!include ../Declarations.puml!DayCellData
!include ../Declarations.puml!PushCellDesigner
!include ../Declarations.puml!PushCellAnimationBehavior
!include ../Declarations.puml!FuturePushCellMouseBehavior
!include ../Declarations.puml!PastPushCellMouseBehavior
!include ../Declarations.puml!PushCellPlacement
!include ../Declarations.puml!PushCellData
!include ../Declarations.puml!CellList
!include ../Declarations.puml!CellGrid
!include ../Declarations.puml!Cell
!include ../Declarations.puml!PushStartCell
!include ../Declarations.puml!PushEndCell
!include ../Declarations.puml!DayCell
!include ../Declarations.puml!DayAdderButton
!include ../Declarations.puml!PushAdderButton

DaysEditor <|.. FullDaysEditor
FullDaysEditor *- CellList
CellList *- CellGrid

FullDaysEditor ..> DaysEditorState
DaysEditorState o--  History

Cell *-- CellDesigner
Cell *-- CellAnimationBehavior
Cell *-- CellPlacement
Cell *-- CellMouseBehavior
Cell *-- CellData

CellDesigner <|... DayCellDesigner
CellAnimationBehavior <|... DayCellAnimationBehavior
CellPlacement <|... DayCellPlacement
CellMouseBehavior <|.... FutureDayCellMouseBehavior
CellMouseBehavior <|..... PastDayCellMouseBehavior
CellData <|... DayCellData

CellDesigner <|.. PushCellDesigner
CellAnimationBehavior <|.. PushCellAnimationBehavior
CellPlacement <|.. PushCellPlacement
CellMouseBehavior <|... FuturePushCellMouseBehavior
CellMouseBehavior <|.. PastPushCellMouseBehavior
CellData <|.. PushCellData

PlaceholderCell --|> Cell
PushStartCell --|> Cell
PushEndCell --|> Cell
DayCell --|> Cell
CellList ----o Cell

CellList <|.. CellListFullFeatured
CellList <|.. CellListNoPush
CellGrid <|.. CellGridFullFeatured
CellGrid <|.. CellGridNoPush



hide members

@enduml